/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-PHYSEC
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_PHYSEC_API_H
#define INCLUDED_PHYSEC_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_PHYSEC_EXPORTS
#define GR_PHYSEC_API __GR_ATTR_EXPORT
#else
#define GR_PHYSEC_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PHYSEC_API_H */
