# Copyright 2011 Free Software Foundation, Inc.
#
# This file was generated by gr_modtool, a tool from the GNU Radio framework
# This file is a part of gr-PHYSEC
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

# This file sets up a CMakeCache entry for the gnuradio-PHYSEC module.
# It is typically placed in the build directory of the module.

set(gnuradio-PHYSEC_FOUND TRUE)

# The following variables are set:
#   gnuradio-PHYSEC_INCLUDE_DIRS - include directories for gnuradio-PHYSEC
#   gnuradio-PHYSEC_LIBRARIES    - libraries to link against
#   gnuradio-PHYSEC_LIBRARY_DIRS - directories containing the libraries
#   gnuradio-PHYSEC_RUNTIME_LIBRARY_DIRS - directories containing the DLLs on Windows

# The cache entry is:
#   gnuradio-PHYSEC_DIR:PATH=/path/to/gnuradio-PHYSEC

# This file is generated by the build system and should not be edited.
# To modify the module, edit the CMakeLists.txt file in the module source directory.

# The following variables are set by the build system:
#   gnuradio-PHYSEC_INCLUDE_DIRS - include directories for gnuradio-PHYSEC
#   gnuradio-PHYSEC_LIBRARIES    - libraries to link against
#   gnuradio-PHYSEC_LIBRARY_DIRS - directories containing the libraries
#   gnuradio-PHYSEC_RUNTIME_LIBRARY_DIRS - directories containing the DLLs on Windows

# The cache entry is:
#   gnuradio-PHYSEC_DIR:PATH=/path/to/gnuradio-PHYSEC

# This file is generated by the build system and should not be edited.
# To modify the module, edit the CMakeLists.txt file in the module source directory.
